class Constants {
  static const TITLE = "Town Square";
  static const UNIQUE_ID_FILE = "unique.id";
  static const EMPTY_STRING = "";
  static const EMPTY_FILE = "empty file";
  static const UNIQUE_ID_LABEL = "Unique ID";
  static const NAME_PADDING = 10.0;
  static const NAME_LABEL = "Name";
  static const NAME_LENGTH = 255;
  static const TEXTFIELD_BORDER_RADIUS = 10.0;
  static const TEXTFIELD_BORDER_WIDTH = 1.0;
  static const EMAIL_HINT_TEXT = "Name";
  static const DEFAULT_NAME = "Anonymous User";
  static const SAVE_SETTINGS_BUTTON_TEXT = "Save";
  static const INFORMED_MESSAGE_FONT_SIZE = 14.0;
  static const PUBLIC_KEY_FILE = "public.key";
  static const PRIVATE_KEY_FILE = "private.key";
  static const SQUARE_FILE_EXT = ".square";
  static const FILE_DATA_SEPERATOR = "~__~";
  static const COMMAND_SEPERATOR = "%%%";
  static const TILDE = "~";
  static const COMMA = ",";
  static const COLON = ":";
  static const int BASE_CLIENT_TYPE = 1;
  static const int BASE_SQUARE_TYPE = 1;
  static const OK_CODE = "200";
  static const INVALID_CODE = "400";
  static const ALREADY_REGISTERED_CODE = "460";
}
